CMBCURTAINCOLOUR = "CMBCURTAINCOLOUR"
CMBNUMWINDROWS = "CMBNUMWINDROWS"
CMBWINDOWTYPEDEFAULT = "CMBWINDOWTYPEDEFAULT"
CMBFLOORSLOPE = "CMBFLOORSLOPE"
CMBWINDPOT = "CMBWINDPOT"

NUMWINDOWSDEFAULT = "NUMWINDOWSDEFAULT"
NUMWINDOWSREQ = "NUMWINDOWSREQ"
NUMEXTRAWINDOWS = "NUMEXTRAWINDOWS"
NUMCURTFINHL = "NUMCURTFINHL"
NUMCURTFINHR = "NUMCURTFINHR"
NUMCURTFINW = "NUMCURTFINW"
NUMFLOORSLOPE = "NUMFLOORSLOPE"
NUMES40PANELSREQ = "NUMES40PANELSREQ"
NUMES40PANELCOLOURED = "NUMES40PANELSCOLOURED"
NUMES40PANELSVISIONCLEAR = "NUMES40PANELSVISIONCLEAR"
NUMES40PANELSVISIONMESH = "NUMES40PANELSVISIONMESH"
NUMPANELHEIGHT = "NUMPANELHEIGHT"  # CONCERTINA only — individual panel height (mm)

CHKSLOPEREQUIRED = "CHKSLOPEREQUIRED"
CHKCUSTBOTTOMEDGE = "CHKCUSTBOTTOMEDGE"
CHKCUSTSCREENPRINT = "CHKCUSTSCREENPRINT"
CHKEMERGZIP = "CHKEMERGZIP"
CHKDRIPEDGE = "CHKDRIPEDGE"
CHKCOMOWEAR = "CHKCOMOWEAR"
CHKEX35BVSEAL = "CHKEX35BVSEAL"
CHKUSEDEFAULTWINPERROW = "CHKUSEDEFAULTWINPERROW"
CHKHS25SPECIAL = "CHKHS25SPECIAL"

WINDOW_ROW_LOCATION_NAMES = tuple(f"CMBWINDROWLOC{index}" for index in range(1, 15))
WINDOW_ROW_TYPE_NAMES = tuple(f"CMBWINDROWTYPE{index}" for index in range(1, 15))

CURTAIN_CONTROL_NAMES = (
    CMBCURTAINCOLOUR,
    CMBNUMWINDROWS,
    CMBWINDOWTYPEDEFAULT,
    CMBFLOORSLOPE,
    CMBWINDPOT,
    NUMWINDOWSDEFAULT,
    NUMWINDOWSREQ,
    NUMEXTRAWINDOWS,
    NUMCURTFINHL,
    NUMCURTFINHR,
    NUMCURTFINW,
    NUMFLOORSLOPE,
    NUMES40PANELSREQ,
    NUMES40PANELCOLOURED,
    NUMES40PANELSVISIONCLEAR,
    NUMES40PANELSVISIONMESH,
    NUMPANELHEIGHT,
    CHKSLOPEREQUIRED,
    CHKCUSTBOTTOMEDGE,
    CHKCUSTSCREENPRINT,
    CHKEMERGZIP,
    CHKDRIPEDGE,
    CHKCOMOWEAR,
    CHKEX35BVSEAL,
    CHKUSEDEFAULTWINPERROW,
    CHKHS25SPECIAL,
    *WINDOW_ROW_LOCATION_NAMES,
    *WINDOW_ROW_TYPE_NAMES,
)
