CMBCONFIGID = "TXTCONFIGID"
CMBJOBTYPE = "CMBJOBTYPE"
CMBFREIGHTRATE = "CMBFREIGHTRATE"
TXTSWINGINSTALLPARTID = "TXTSWINGINSTALLPARTID"
TXTLUMPSUMDESC = "TXTLUMPSUMDESC"

CHKISPAIR = "CHKISPAIR"
CHKALDISPEC = "CHKALDISPEC"
CHKINSGANTRY = "CHKINSGANTRY"

CHKINSSTRIPSM = "CHKINSSTRIPSM"
CHKINSSTRIPLG = "CHKINSSTRIPLG"
CHKINSSTRIPREP = "CHKINSSTRIPREP"
CHKLABSTRIPREMOVAL = "CHKLABSTRIPREMOVAL"
CHKLABSLDREMOVAL = "CHKLABSLDREMOVAL"

CHKINSSWIS = "CHKINSSWIS"
CHKINSSWIP = "CHKINSSWIP"
CHKINSREPPNLS = "CHKINSREPPNLS"
CHKINSREPPNLP = "CHKINSREPPNLP"
CHKLABSWIREMOVAL = "CHKLABSWIREMOVAL"
CHKSWIDISPOSAL = "CHKSWIDISPOSAL"
CHKINSFACT = "CHKINSFACT"

CHKINS50SWIS = "CHKINS50SWIS"
CHKINS50SWIP = "CHKINS50SWIP"
CHKINSSLD = "CHKINSSLD"
CHKINSCAP = "CHKINSCAP"

CHKINSRRD4X4 = "CHKINSRRD4X4"
CHKINSRRD6X6 = "CHKINSRRD6X6"
CHKINSHSDFOLDING = "CHKINSHSDFOLDING"
CHKLABRRDREMOVAL = "CHKLABRRDREMOVAL"
CHKLABRRDDISPOSAL = "CHKLABRRDDISPOSAL"
CHKINSPACK = "CHKINSPACK"

CHKINSENT4X4 = "CHKINSENT4X4"
CHKINSENT6X6 = "CHKINSENT6X6"

CHKINSHSDSECTIONAL = "CHKINSHSDSECTIONAL"
CHKINSSHUTTER5X5 = "CHKINSSHUTTER5X5"
CHKINSSHUTTER5X5PLUS = "CHKINSSHUTTER5X5PLUS"
CHKINSBOL = "CHKINSBOL"

CHKLIFTINGFRAME = "CHKLIFTINGFRAME"
CHKASSAREMOVAL = "CHKASSAREMOVAL"
CHKSPAREISOLATOR = "CHKSPAREISOLATOR"
CHKROLLERSHUTTERREMOVAL = "CHKROLLERSHUTTERREMOVAL"
CHKLABSITEASS = "CHKLABSITEASS"
CHKLABSITEATT = "CHKLABSITEATT"
CHKINSAH = "CHKINSAH"
CHKRETURNTRIP = "CHKRETURNTRIP"
CHKACCOM = "CHKACCOM"

NUMSTRIPAREA = "NUMSTRIPAREA"
NUMRETURN_COST = "NUMRETURNCOST"
NUMDRIVINGTIME = "NUMDRIVINGTIME"
NUMTOTALDOORSPROJ = "NUMTOTALDOORSPROJ"
NUMESTPROJECTSONRUN = "NUMESTPROJECTSONRUN"
NUMACCOMNIGHT = "NUMACCOMNIGHT"
NUMPERSONINSTALL = "NUMPERSONINSTALL"
NUMLUMSUM = "NUMLUMSUM"
NUMFREIGHTALLOWANCE = "NUMFREIGHTALLOWANCE"

CHECKBOX_CONTROL_NAMES = (
    CHKISPAIR,
    CHKALDISPEC,
    CHKINSGANTRY,
    CHKINSSTRIPSM,
    CHKINSSTRIPLG,
    CHKINSSTRIPREP,
    CHKLABSTRIPREMOVAL,
    CHKLABSLDREMOVAL,
    CHKINSSWIS,
    CHKINSSWIP,
    CHKINSREPPNLS,
    CHKINSREPPNLP,
    CHKLABSWIREMOVAL,
    CHKSWIDISPOSAL,
    CHKINSFACT,
    CHKINS50SWIS,
    CHKINS50SWIP,
    CHKINSSLD,
    CHKINSCAP,
    CHKINSRRD4X4,
    CHKINSRRD6X6,
    CHKINSHSDFOLDING,
    CHKLABRRDREMOVAL,
    CHKLABRRDDISPOSAL,
    CHKINSPACK,
    CHKINSENT4X4,
    CHKINSENT6X6,
    CHKINSHSDSECTIONAL,
    CHKINSSHUTTER5X5,
    CHKINSSHUTTER5X5PLUS,
    CHKINSBOL,
    CHKLIFTINGFRAME,
    CHKASSAREMOVAL,
    CHKSPAREISOLATOR,
    CHKROLLERSHUTTERREMOVAL,
    CHKLABSITEASS,
    CHKLABSITEATT,
    CHKINSAH,
    CHKRETURNTRIP,
    CHKACCOM,
)

NUMBER_CONTROL_NAMES = (
    NUMSTRIPAREA,
    NUMRETURN_COST,
    NUMDRIVINGTIME,
    NUMTOTALDOORSPROJ,
    NUMESTPROJECTSONRUN,
    NUMACCOMNIGHT,
    NUMPERSONINSTALL,
    NUMLUMSUM,
    NUMFREIGHTALLOWANCE,
    CMBFREIGHTRATE,
)

INSTALLATION_CONTROL_NAMES = (
    CMBCONFIGID,
    CMBJOBTYPE,
    CMBFREIGHTRATE,
    TXTSWINGINSTALLPARTID,
    TXTLUMPSUMDESC,
    *CHECKBOX_CONTROL_NAMES,
    *NUMBER_CONTROL_NAMES,
)
