CMBDOORMODEL = "CMBDOORMODEL"
NUMDOORHEIGHT = "NUMDOORHEIGHT"
NUMDOORWIDTH = "NUMDOORWIDTH"
QTY = "QTY"

CMBGPOISO = "CMBGPOISO"
CMBMOTORORIDE = "CMBMOTORORIDE"
CMBTRACKCONFIG = "CMBTRACKCONFIG"
CMBWINDTRACK = "CMBWINDTRACK"
CMBPOWERSUPPLY = "CMBPOWERSUPPLY"
CMBCONTROLLERENCLOSURE = "CMBCONTROLLERENCLOSURE"
CMBMOTORSHROUD = "CMBMOTORSHROUD"
CMBMOTORSPEC = "CMBMOTORSPEC"
CMBBRAKEIPBASIC = "CMBBRAKEIPBASIC"
CMBBRUSHSEAL = "CMBBRUSHSEAL"
CMBTRAFFICLIGHT = "CMBTRAFFICLIGHT"
CMBPEBEAMS = "CMBPEBEAMS"
CMBUPS = "CMBUPS"
CMBCUSTSTEEL = "CMBCUSTSTEEL"
CMBREARHOODBRUSHSEAL = "CMBREARHOODBRUSHSEAL"
CMBSPECIALCONDUIT = "CMBSPECIALCONDUIT"
CMBCOLOURFINISHTYPE = "CMBCOLOURFINISHTYPE"
CMBES40FASCIA = "CMBES40FASCIA"
CMBES40VSDMTR = "CMBES40VSDMTR"
CMBHEATTRACELEG = "CMBHEATTRACELEG"
CMBGEARBOXHEATER = "CMBGEARBOXHEATER"
CMBHEATTRACEHOOD = "CMBHEATTRACEHOOD"
CMBFELTSEAL = "CMBFELTSEAL"
CMBCABLELENGTH = "CMBCABLELENGTH"
CMBELECSPEC = "CMBELECSPEC"
CMBCURTAINCOLOUR = "CMBCURTAINCOLOUR"
CMBMOTORHAND = "CMBMOTORHAND"

CMBPED1 = "CMBPED1"
CMBPED2 = "CMBPED2"
CMBRADAR1 = "CMBRADAR1"
CMBRADAR2 = "CMBRADAR2"
CMBACT1 = "CMBACT1"
CMBACT2 = "CMBACT2"
CMBACT3 = "CMBACT3"
CMBACT4 = "CMBACT4"
CMBACT5 = "CMBACT5"
NUMREMOTEQTY1 = "NUMREMOTEQTY1"
NUMREMOTEQTY2 = "NUMREMOTEQTY2"
NUMREMOTEQTY3 = "NUMREMOTEQTY3"
NUMREMOTEQTY4 = "NUMREMOTEQTY4"
CMBFLOORLOOPINSTALL = "CMBFLOORLOOPINSTALL"

CHKHYPERLIFT = "CHKHYPERLIFT"
CHKHOLDOPEN = "CHKHOLDOPEN"
CHKINTERLOCK = "CHKINTERLOCK"
CHKSTAINLESS = "CHKSTAINLESS"
CHKEX35FELT = "CHKEX35FELT"
CHKMOTORCLEARCOAT = "CHKMOTORCLEARCOAT"

VISIBLE_DOOR_CONTROL_NAMES = (
    CMBDOORMODEL,
    NUMDOORHEIGHT,
    NUMDOORWIDTH,
    QTY,
    CMBGPOISO,
    CMBMOTORORIDE,
    CMBTRACKCONFIG,
    CMBWINDTRACK,
    CMBELECSPEC,
    CMBPOWERSUPPLY,
    CMBCONTROLLERENCLOSURE,
    CMBMOTORSHROUD,
    CMBMOTORSPEC,
    CMBBRUSHSEAL,
    CMBTRAFFICLIGHT,
    CMBPEBEAMS,
    CMBUPS,
    CMBCUSTSTEEL,
    CMBREARHOODBRUSHSEAL,
    CMBSPECIALCONDUIT,
    CMBCOLOURFINISHTYPE,
    CMBES40FASCIA,
    CMBES40VSDMTR,
    CMBHEATTRACELEG,
    CMBGEARBOXHEATER,
    CMBHEATTRACEHOOD,
    CMBFELTSEAL,
    CMBPED1,
    CMBPED2,
    CMBRADAR1,
    CMBRADAR2,
    CMBACT1,
    CMBACT2,
    CMBACT3,
    CMBACT4,
    NUMREMOTEQTY1,
    NUMREMOTEQTY2,
    NUMREMOTEQTY3,
    NUMREMOTEQTY4,
    CMBFLOORLOOPINSTALL,
    CHKHYPERLIFT,
    CHKHOLDOPEN,
    CHKINTERLOCK,
    CHKSTAINLESS,
    CHKEX35FELT,
    CHKMOTORCLEARCOAT,
)

HIDDEN_DEFAULT_CONTROL_NAMES = (
    CMBBRAKEIPBASIC,
    CMBCABLELENGTH,
    CMBCURTAINCOLOUR,
    CMBMOTORHAND,
    CMBACT5,
)

DOOR_CONTROL_NAMES = VISIBLE_DOOR_CONTROL_NAMES + HIDDEN_DEFAULT_CONTROL_NAMES
