-- =============================================================================
-- APPLY EVERYTHING TO THE RRD MOVIDOR TEMPLATE
--
-- One script, run top to bottom, that brings a RP_config database up to the
-- agreed definition of RRD-MOVIDOR-TEMPLATE. Safe to run more than once: every
-- part is an idempotent UPDATE or an insert guarded by IF NOT EXISTS.
--
--   Part 1  Sections          51 parameters get their "Step > Group" section
--   Part 2  Activation rules  condition + quantity formulas for 21 rules
--   Part 3  Missing rules     RRD-63 / RRD-64, inserted only if absent
--   Part 4  Report            what the database looks like afterwards
--
-- Wrapped in a single transaction. If any part fails nothing is applied -- a
-- half-configured rule set is worse than an unchanged one.
--
-- GENERATED by scratchpad/gen_master.py from rrd_movidor_sections.csv and
-- set_activation_rule_formulas.sql, so the row lists cannot drift from them.
--
-- BEFORE RUNNING: take a backup. db/backups/ holds point-in-time snapshots.
--
-- Every formula in Part 2 was checked against
-- backend/app/pricing_rules/movidor_upgrade_rules.py over 400 randomised
-- configurations with no mismatches. uCfgRules does not price quotes yet, so
-- this changes no live price -- it makes the data match the code.
-- =============================================================================

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

DECLARE @Cfg INT = (
    SELECT TOP 1 CfgID FROM dbo.uCfgConfigurators
    WHERE PartID = N'RRD-MOVIDOR-TEMPLATE'
);
IF @Cfg IS NULL
BEGIN
    RAISERROR('RRD-MOVIDOR-TEMPLATE not found - wrong database?', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END;

IF COL_LENGTH('dbo.uCfgParameters', 'Section') IS NULL
BEGIN
    RAISERROR('uCfgParameters.Section is missing. Run db/uCfg_add_section.sql (PART 1 ONLY - its part 2 overwrites sections with the old Streamlit names), then re-run this.', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END;

-- -- Part 1: sections ---------------------------------------------------------
-- "Step > Group" splits into a wizard step and a heading inside it. Without
-- this the form renders one flat list per step.
DECLARE @S TABLE (ControlName NVARCHAR(50) PRIMARY KEY, Section NVARCHAR(50));
INSERT INTO @S (ControlName, Section) VALUES
    (N'CMBDOORMODEL', N'Door'),
    (N'NUMDOORHEIGHT', N'Door'),
    (N'NUMDOORWIDTH', N'Door'),
    (N'QTY', N'Door'),
    (N'CMBGPOISO', N'Overview > Controller'),
    (N'CMBMOTORHAND', N'Overview > Controller'),
    (N'CMBMOTORORIDE', N'Overview > Controller'),
    (N'CMBTRACKCONFIG', N'Overview > Tracks'),
    (N'CMBWINDTRACK', N'Overview > Tracks'),
    (N'CMBELECSPEC', N'Overview > Power'),
    (N'CMBPOWERSUPPLY', N'Overview > Power'),
    (N'CMBCABLELENGTH', N'Overview > Controller'),
    (N'CMBCONTROLLERENCLOSURE', N'Upgrades / Common Options > Enclosure & Motor'),
    (N'CMBMOTORSHROUD', N'Upgrades / Common Options > Enclosure & Motor'),
    (N'CMBMOTORSPEC', N'Upgrades / Common Options > Enclosure & Motor'),
    (N'CMBBRAKEIPBASIC', N'Upgrades / Common Options > Enclosure & Motor'),
    (N'CHKMOTORCLEARCOAT', N'Upgrades / Common Options > Enclosure & Motor'),
    (N'CMBBRUSHSEAL', N'Upgrades / Common Options > Seals & Safety'),
    (N'CMBTRAFFICLIGHT', N'Upgrades / Common Options > Seals & Safety'),
    (N'CMBPEBEAMS', N'Upgrades / Common Options > Seals & Safety'),
    (N'CHKHYPERLIFT', N'Options > Tick Options'),
    (N'CHKHOLDOPEN', N'Options > Tick Options'),
    (N'CHKINTERLOCK', N'Options > Tick Options'),
    (N'CHKSTAINLESS', N'Options > Tick Options'),
    (N'CHKEX35FELT', N'Options > Tick Options'),
    (N'CMBUPS', N'Options > Finish & Extras'),
    (N'CMBCUSTSTEEL', N'Options > Finish & Extras'),
    (N'CMBREARHOODBRUSHSEAL', N'Options > Finish & Extras'),
    (N'CMBSPECIALCONDUIT', N'Options > Finish & Extras'),
    (N'CMBCOLOURFINISHTYPE', N'Options > Finish & Extras'),
    (N'CMBCURTAINCOLOUR', N'Options > Finish & Extras'),
    (N'CMBES40FASCIA', N'ES40 Only'),
    (N'CMBES40VSDMTR', N'ES40 Only'),
    (N'CMBHEATTRACELEG', N'Thermic + Movichill Only'),
    (N'CMBHEATTRACEHOOD', N'Thermic + Movichill Only'),
    (N'CMBGEARBOXHEATER', N'Thermic + Movichill Only'),
    (N'CMBFELTSEAL', N'Thermic + Movichill Only'),
    (N'CMBPED1', N'Activations > Buttons & Radars'),
    (N'CMBPED2', N'Activations > Buttons & Radars'),
    (N'CMBRADAR1', N'Activations > Buttons & Radars'),
    (N'CMBRADAR2', N'Activations > Buttons & Radars'),
    (N'CMBACT1', N'Activations > Activation Slots'),
    (N'NUMREMOTEQTY1', N'Activations > Activation Slots'),
    (N'CMBACT2', N'Activations > Activation Slots'),
    (N'NUMREMOTEQTY2', N'Activations > Activation Slots'),
    (N'CMBACT3', N'Activations > Activation Slots'),
    (N'NUMREMOTEQTY3', N'Activations > Activation Slots'),
    (N'CMBACT4', N'Activations > Activation Slots'),
    (N'NUMREMOTEQTY4', N'Activations > Activation Slots'),
    (N'CMBACT5', N'Activations > Activation Slots'),
    (N'CMBFLOORLOOPINSTALL', N'Activations > Activation Slots');

UPDATE p
SET p.Section = s.Section
FROM dbo.uCfgParameters p
JOIN @S s ON UPPER(s.ControlName) = UPPER(p.ControlName)
WHERE p.CfgID = @Cfg
  AND (p.Section IS NULL OR p.Section <> s.Section);

DECLARE @SectionsChanged INT = @@ROWCOUNT;

-- -- Part 2: activation rule formulas -----------------------------------------
DECLARE @F TABLE (
    RuleCode    NVARCHAR(30) PRIMARY KEY,
    CondFormula NVARCHAR(500),
    QtyFormula  NVARCHAR(500) NULL,
    QtyUnit     NVARCHAR(30),
    Note        NVARCHAR(400)
);

INSERT INTO @F (RuleCode, CondFormula, QtyFormula, QtyUnit, Note) VALUES
-- ── Radars: one assembly per radar set to that sensor ────────────────────────
 (N'RRD-27', N'countEquals(group("CMBRADAR"), "IXIO Sensor - Long Stalk") > 0',    N'countEquals(group("CMBRADAR"), "IXIO Sensor - Long Stalk")',    N'Per Radar', N'One per radar set to IXIO Sensor - Long Stalk.')
,(N'RRD-28', N'countEquals(group("CMBRADAR"), "IXIO Sensor - Short Stalk") > 0',   N'countEquals(group("CMBRADAR"), "IXIO Sensor - Short Stalk")',   N'Per Radar', N'One per radar set to IXIO Sensor - Short Stalk.')
,(N'RRD-29', N'countEquals(group("CMBRADAR"), "IXIO Sensor - No Stalk") > 0',      N'countEquals(group("CMBRADAR"), "IXIO Sensor - No Stalk")',      N'Per Radar', N'One per radar set to IXIO Sensor - No Stalk.')
,(N'RRD-30', N'countEquals(group("CMBRADAR"), "Condor Radar - Long Stalk") > 0',   N'countEquals(group("CMBRADAR"), "Condor Radar - Long Stalk")',   N'Per Radar', N'One per radar set to Condor Radar - Long Stalk.')
,(N'RRD-31', N'countEquals(group("CMBRADAR"), "Condor Radar - Short Stalk") > 0',  N'countEquals(group("CMBRADAR"), "Condor Radar - Short Stalk")',  N'Per Radar', N'One per radar set to Condor Radar - Short Stalk.')
,(N'RRD-32', N'countEquals(group("CMBRADAR"), "Condor Radar - No Stalk") > 0',     N'countEquals(group("CMBRADAR"), "Condor Radar - No Stalk")',     N'Per Radar', N'One per radar set to Condor Radar - No Stalk.')
,(N'RRD-33', N'countEquals(group("CMBRADAR"), "Falcon Radar - Long Stalk") > 0',   N'countEquals(group("CMBRADAR"), "Falcon Radar - Long Stalk")',   N'Per Radar', N'One per radar set to Falcon Radar - Long Stalk.')
,(N'RRD-34', N'countEquals(group("CMBRADAR"), "Falcon Radar - Short Stalk") > 0',  N'countEquals(group("CMBRADAR"), "Falcon Radar - Short Stalk")',  N'Per Radar', N'One per radar set to Falcon Radar - Short Stalk.')
,(N'RRD-35', N'countEquals(group("CMBRADAR"), "Falcon Radar - No Stalk") > 0',     N'countEquals(group("CMBRADAR"), "Falcon Radar - No Stalk")',     N'Per Radar', N'One per radar set to Falcon Radar - No Stalk.')

-- ── Activation slots counted directly (no quantity box) ──────────────────────
,(N'RRD-37', N'countStartsWith(group("CMBACT"), "Pull Cord") > 0',                 N'countStartsWith(group("CMBACT"), "Pull Cord")',                 N'Per Slot',  N'One switch per activation slot starting "Pull Cord". Pull cords have no NUMREMOTEQTY.')

-- ── Activation slots x their quantity box (the remote count) ─────────────────
,(N'RRD-38', N'sumWhere(group("CMBACT"), "Magic Switch - In Wall", group("NUMREMOTEQTY"), "equals") > 0',      N'sumWhere(group("CMBACT"), "Magic Switch - In Wall", group("NUMREMOTEQTY"), "equals")',      N'Per Remote', N'Sums NUMREMOTEQTY beside each slot exactly equal to "Magic Switch - In Wall".')
,(N'RRD-40', N'sumWhere(group("CMBACT"), "Magic Switch - IP65 Housing", group("NUMREMOTEQTY"), "equals") > 0', N'sumWhere(group("CMBACT"), "Magic Switch - IP65 Housing", group("NUMREMOTEQTY"), "equals")', N'Per Remote', N'Sums NUMREMOTEQTY beside each slot exactly equal to "Magic Switch - IP65 Housing".')
,(N'RRD-43', N'sumWhere(group("CMBACT"), "Pentacode - 2", group("NUMREMOTEQTY")) > 0',      N'sumWhere(group("CMBACT"), "Pentacode - 2", group("NUMREMOTEQTY"))',      N'Per Remote', N'Sums NUMREMOTEQTY across slots starting "Pentacode - 2".')
,(N'RRD-44', N'sumWhere(group("CMBACT"), "Pentacode - 4", group("NUMREMOTEQTY")) > 0',      N'sumWhere(group("CMBACT"), "Pentacode - 4", group("NUMREMOTEQTY"))',      N'Per Remote', N'Sums NUMREMOTEQTY across slots starting "Pentacode - 4". NOTE: part is RRD-ELREM1C-PC but the driver is the 4-button count - copied from the live engine, worth confirming against M1.')
,(N'RRD-45', N'sumWhere(group("CMBACT"), "Elsema Remote - 1", group("NUMREMOTEQTY")) > 0',  N'sumWhere(group("CMBACT"), "Elsema Remote - 1", group("NUMREMOTEQTY"))',  N'Per Remote', N'Sums NUMREMOTEQTY across slots starting "Elsema Remote - 1".')
,(N'RRD-46', N'sumWhere(group("CMBACT"), "Elsema Remote - 2", group("NUMREMOTEQTY")) > 0',  N'sumWhere(group("CMBACT"), "Elsema Remote - 2", group("NUMREMOTEQTY"))',  N'Per Remote', N'Sums NUMREMOTEQTY across slots starting "Elsema Remote - 2".')
,(N'RRD-47', N'sumWhere(group("CMBACT"), "Elsema Remote - 4", group("NUMREMOTEQTY")) > 0',  N'sumWhere(group("CMBACT"), "Elsema Remote - 4", group("NUMREMOTEQTY"))',  N'Per Remote', N'Sums NUMREMOTEQTY across slots starting "Elsema Remote - 4".')
,(N'RRD-48', N'sumWhere(group("CMBACT"), "Elsema Remote - 8", group("NUMREMOTEQTY")) > 0',  N'sumWhere(group("CMBACT"), "Elsema Remote - 8", group("NUMREMOTEQTY"))',  N'Per Remote', N'Sums NUMREMOTEQTY across slots starting "Elsema Remote - 8".')

-- ── Fires once regardless of how many slots match ────────────────────────────
,(N'RRD-39', N'sumWhere(group("CMBACT"), "Magic Switch - In Wall", group("NUMREMOTEQTY"), "equals") > 0', NULL, N'Per Door', N'One cable whenever RRD-38 applies, regardless of quantity.')
,(N'RRD-41', N'countStartsWith(group("CMBACT"), "Elsema Remote") > 0 or countStartsWith(group("CMBACT"), "Elsema Receiver") > 0', NULL, N'Per Door', N'One receiver if any slot starts "Elsema Remote" or "Elsema Receiver".')
,(N'RRD-42', N'countStartsWith(group("CMBACT"), "Pentacode - 2") > 0 or countStartsWith(group("CMBACT"), "Pentacode - 4") > 0', NULL, N'Per Door', N'One receiver if any slot starts "Pentacode - 2" or "Pentacode - 4".')
;
UPDATE r
SET r.ConditionFormula = f.CondFormula,
    r.QuantityFormula  = f.QtyFormula,
    r.QuantityUnit     = f.QtyUnit,
    r.Notes            = f.Note
FROM dbo.uCfgRules r
JOIN @F f ON f.RuleCode = r.RuleCode
WHERE r.CfgID = @Cfg;

DECLARE @RulesChanged INT = @@ROWCOUNT;

-- Refuse to half-apply. If a rule code is absent the two databases have
-- diverged, and quietly configuring the subset that happens to exist would
-- leave the rest firing on every quote with nobody the wiser.
DECLARE @Missing NVARCHAR(1000) = (
    SELECT STRING_AGG(f.RuleCode, ', ')
    FROM @F f
    WHERE NOT EXISTS (SELECT 1 FROM dbo.uCfgRules r
                      WHERE r.CfgID = @Cfg AND r.RuleCode = f.RuleCode)
);
IF @Missing IS NOT NULL
BEGIN
    RAISERROR('These rule codes are not in this database: %s. Nothing applied - reconcile the rule sets first.', 16, 1, @Missing);
    ROLLBACK TRANSACTION;
    RETURN;
END;

-- -- Part 3: rules in the M1 workbooks with no rule here -----------------------
-- Each is the missing half of a pair whose other half is configured, so the
-- part is simply never added to a quote. Both exist in M1 and price correctly.
IF NOT EXISTS (SELECT 1 FROM dbo.uCfgRules WHERE CfgID = @Cfg AND RuleCode = N'RRD-63')
BEGIN
    INSERT INTO dbo.uCfgRules
        (CfgID, RuleCode, Name, Category, ResultPartID, Quantity, QuantityUnit,
         ConditionFormula, Notes, IsActive)
    VALUES
        (@Cfg, N'RRD-63', N'ES40 Narrow Fascia', N'ASSEMBLY_UPGRADE',
         N'RRD-FASASS-ES40-3', N'1', N'Per Door', N'NUMDOORWIDTH <= 3000',
         N'Pairs with RRD-12 (> 3000). Width is in the formula because the operator list has no <=.', 1);

    DECLARE @R63 INT = (SELECT RuleID FROM dbo.uCfgRules WHERE CfgID = @Cfg AND RuleCode = N'RRD-63');
    INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue)
    VALUES (@R63, 1, N'CMBDOORMODEL',  N'equals', N'ES40'),
           (@R63, 1, N'CMBES40FASCIA', N'equals', N'Yes');
END;

IF NOT EXISTS (SELECT 1 FROM dbo.uCfgRules WHERE CfgID = @Cfg AND RuleCode = N'RRD-64')
BEGIN
    -- Inserted INACTIVE. A blank motor hand counts as Left in M1, so switching
    -- this on starts adding a cover to existing Concertina/Movifold quotes that
    -- specify the stainless shroud but no hand. Correct, but it moves prices --
    -- a deliberate act, not a side effect of running a script.
    INSERT INTO dbo.uCfgRules
        (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision,
         Quantity, QuantityUnit, Notes, IsActive)
    VALUES
        (@Cfg, N'RRD-64', N'Left-Hand Stainless-Steel Motor Cover',
         N'ASSEMBLY_UPGRADE', N'RRD-MOTCOV-CONC-LH', N'E', N'1', N'Per Door',
         N'Pairs with RRD-25 (right hand). A blank motor hand counts as Left, so this is the default cover.', 0);

    DECLARE @R64 INT = (SELECT RuleID FROM dbo.uCfgRules WHERE CfgID = @Cfg AND RuleCode = N'RRD-64');
    INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue)
    VALUES (@R64, 1, N'CMBDOORMODEL',   N'in',         N'MOVIFOLD, CONCERTINA'),
           (@R64, 1, N'CMBMOTORHAND',   N'not_equals', N'Right'),
           (@R64, 1, N'CMBMOTORSHROUD', N'equals',     N'Yes - Stainless Steel Upgrade');
END;

COMMIT TRANSACTION;

-- -- Part 4: report -----------------------------------------------------------
PRINT '--- Applied ---';
PRINT '  parameters re-sectioned : ' + CAST(@SectionsChanged AS VARCHAR);
PRINT '  rules given formulas    : ' + CAST(@RulesChanged AS VARCHAR);

SELECT Section, COUNT(*) AS Parameters
FROM dbo.uCfgParameters WHERE CfgID = @Cfg
GROUP BY Section ORDER BY Section;

SELECT r.RuleCode, r.Name, r.ResultPartID
FROM dbo.uCfgRules r
WHERE r.CfgID = @Cfg AND r.IsActive = 1
  AND (r.ConditionFormula IS NULL OR LTRIM(RTRIM(r.ConditionFormula)) = '')
  AND NOT EXISTS (SELECT 1 FROM dbo.uCfgRuleConditions c WHERE c.RuleID = r.RuleID)
ORDER BY r.RuleCode;

PRINT '';
PRINT 'The second result set is every ACTIVE rule with no condition and no';
PRINT 'condition formula - each one applies to every quote. Expect it empty.';
PRINT 'Restart the API afterwards if it was running before the change.';
