/* ---------------------------------------------------------------------------
   RESTORE the RRD Movidor parameters + options after an import wiped them.

   A parameter CSV import replaces the whole set: control names missing from
   the file are deleted, together with their options. Rules, rule conditions,
   defaults and validations are keyed by ControlName text (no FK to ParamID),
   so they SURVIVED and are deliberately left alone here.

   This restores dbo.uCfgParameters + dbo.uCfgParameterOptions only.
   Re-runnable. It does NOT touch uCfgDefaults, uCfgRules or uCfgRuleConditions.
--------------------------------------------------------------------------- */

/* AUTO-GENERATED from the Python dicts by db/seed_movidor.py. Re-runnable. */
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.uCfgConfigurators WHERE PartID = N'RRD-MOVIDOR-TEMPLATE')
    INSERT INTO dbo.uCfgConfigurators (PartID, PartRevision, PartDescription, ConfiguratorName, DoorType) VALUES (N'RRD-MOVIDOR-TEMPLATE', N'A', N'RRD Movidor configurator template', N'RRD Movidor', N'RRD');
DECLARE @Cfg INT = (SELECT TOP 1 CfgID FROM dbo.uCfgConfigurators WHERE PartID = N'RRD-MOVIDOR-TEMPLATE');
DECLARE @P INT;

-- Clear this configurator's existing definition (idempotent re-run)
DELETE o FROM dbo.uCfgParameterOptions o JOIN dbo.uCfgParameters p ON o.ParamID = p.ParamID WHERE p.CfgID = @Cfg;
DELETE FROM dbo.uCfgParameters WHERE CfgID = @Cfg;

-- Parameters (from movidor_control_names.py)
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBDOORMODEL', N'CMBDOORMODEL', N'dropdown', 1, 1);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMDOORHEIGHT', N'NUMDOORHEIGHT', N'number', 1, 2);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMDOORWIDTH', N'NUMDOORWIDTH', N'number', 1, 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'QTY', N'QTY', N'number', 1, 4);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBGPOISO', N'CMBGPOISO', N'dropdown', 1, 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORORIDE', N'CMBMOTORORIDE', N'dropdown', 1, 6);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBTRACKCONFIG', N'CMBTRACKCONFIG', N'dropdown', 1, 7);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBWINDTRACK', N'CMBWINDTRACK', N'dropdown', 1, 8);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBELECSPEC', N'CMBELECSPEC', N'dropdown', 1, 9);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPOWERSUPPLY', N'CMBPOWERSUPPLY', N'dropdown', 1, 10);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCONTROLLERENCLOSURE', N'CMBCONTROLLERENCLOSURE', N'dropdown', 1, 11);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORSHROUD', N'CMBMOTORSHROUD', N'dropdown', 1, 12);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORSPEC', N'CMBMOTORSPEC', N'dropdown', 1, 13);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBBRUSHSEAL', N'CMBBRUSHSEAL', N'dropdown', 1, 14);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBTRAFFICLIGHT', N'CMBTRAFFICLIGHT', N'dropdown', 1, 15);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPEBEAMS', N'CMBPEBEAMS', N'dropdown', 1, 16);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBUPS', N'CMBUPS', N'dropdown', 1, 17);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCUSTSTEEL', N'CMBCUSTSTEEL', N'dropdown', 1, 18);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBREARHOODBRUSHSEAL', N'CMBREARHOODBRUSHSEAL', N'dropdown', 1, 19);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBSPECIALCONDUIT', N'CMBSPECIALCONDUIT', N'dropdown', 1, 20);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCOLOURFINISHTYPE', N'CMBCOLOURFINISHTYPE', N'dropdown', 1, 21);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBES40FASCIA', N'CMBES40FASCIA', N'dropdown', 1, 22);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBES40VSDMTR', N'CMBES40VSDMTR', N'dropdown', 1, 23);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBHEATTRACELEG', N'CMBHEATTRACELEG', N'dropdown', 1, 24);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBGEARBOXHEATER', N'CMBGEARBOXHEATER', N'dropdown', 1, 25);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBHEATTRACEHOOD', N'CMBHEATTRACEHOOD', N'dropdown', 1, 26);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBFELTSEAL', N'CMBFELTSEAL', N'dropdown', 1, 27);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPED1', N'CMBPED1', N'dropdown', 1, 28);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPED2', N'CMBPED2', N'dropdown', 1, 29);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBRADAR1', N'CMBRADAR1', N'dropdown', 1, 30);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBRADAR2', N'CMBRADAR2', N'dropdown', 1, 31);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT1', N'CMBACT1', N'dropdown', 1, 32);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT2', N'CMBACT2', N'dropdown', 1, 33);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT3', N'CMBACT3', N'dropdown', 1, 34);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT4', N'CMBACT4', N'dropdown', 1, 35);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY1', N'NUMREMOTEQTY1', N'number', 1, 36);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY2', N'NUMREMOTEQTY2', N'number', 1, 37);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY3', N'NUMREMOTEQTY3', N'number', 1, 38);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY4', N'NUMREMOTEQTY4', N'number', 1, 39);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBFLOORLOOPINSTALL', N'CMBFLOORLOOPINSTALL', N'dropdown', 1, 40);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKHYPERLIFT', N'CHKHYPERLIFT', N'checkbox', 1, 41);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKHOLDOPEN', N'CHKHOLDOPEN', N'checkbox', 1, 42);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKINTERLOCK', N'CHKINTERLOCK', N'checkbox', 1, 43);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKSTAINLESS', N'CHKSTAINLESS', N'checkbox', 1, 44);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKEX35FELT', N'CHKEX35FELT', N'checkbox', 1, 45);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKMOTORCLEARCOAT', N'CHKMOTORCLEARCOAT', N'checkbox', 1, 46);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBBRAKEIPBASIC', N'CMBBRAKEIPBASIC', N'dropdown', 0, 47);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCABLELENGTH', N'CMBCABLELENGTH', N'dropdown', 0, 48);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCURTAINCOLOUR', N'CMBCURTAINCOLOUR', N'dropdown', 0, 49);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORHAND', N'CMBMOTORHAND', N'dropdown', 0, 50);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT5', N'CMBACT5', N'dropdown', 0, 51);

-- Options (from movidor_option_registery.py, matched to Movidor controls)
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBDOORMODEL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'ES40', N'ES40', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'EX35', N'EX35', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'EX45', N'EX45', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS35', N'HS35', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS35-THERMIC', N'HS35-THERMIC', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS50', N'HS50', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS50-THERMIC', N'HS50-THERMIC', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS65', N'HS65', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVICHILL', N'MOVICHILL', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVICHILL-XL', N'MOVICHILL-XL', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVIFOLD', N'MOVIFOLD', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'CONCERTINA', N'CONCERTINA', 13);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBGPOISO');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'GPO', N'GPO', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Isolator', N'Isolator', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORORIDE');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Hand Crank', N'Hand Crank', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Chain Drive', N'Chain Drive', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBTRACKCONFIG');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Proud', N'Proud', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Concealed', N'Concealed', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBWINDTRACK');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Available', N'Not Available', 4);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBELECSPEC');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Standard', N'Standard', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Carwash', N'Carwash', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPOWERSUPPLY');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P10A', N'1-Ph 10A + N + E', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P15A', N'1-Ph 15A + N + E', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P20A', N'1-Ph 20A + N + E', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P10A', N'3-Ph 10A + N + E', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P15A', N'3-Ph 15A + N + E', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P20A', N'3-Ph 20A + N + E', 7);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBCONTROLLERENCLOSURE');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Std ABS IP54', N'Std ABS IP54', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'ABS Hi-Box IP66', N'ABS Hi-Box IP66', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Remax S/S IP66', N'Remax S/S IP66', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Powdercoated IP66 (S/S)', N'Powdercoated IP66 (S/S)', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORSHROUD');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Stainless Steel Upgrade', N'Yes - Stainless Steel Upgrade', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORSPEC');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IP65 Std', N'IP65 Std', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IP66 Brake Cover', N'IP66 Brake Cover', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBTRAFFICLIGHT');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPEBEAMS');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1 Level PE', N'1 Level PE', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2 Level PE', N'2 Level PE', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Light Curtain - 1830mm', N'Light Curtain - 1830mm', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1 Level - Slimline', N'1 Level - Slimline', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2x LZRS25', N'2x LZRS25', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBUPS');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No UPS', N'No UPS', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1kVA UPS - 10A', N'1kVA UPS - 10A', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2kVA UPS - 10A', N'2kVA UPS - 10A', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3kVA UPS - 15A', N'3kVA UPS - 15A', 4);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBCUSTSTEEL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'PACKER-DADO', N'Packers - Dado', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'PACKERS', N'Packers - Full Perimeter', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'SOB-1FG', N'1-Fold 3mm Gal', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'SOB-4FG', N'3mm Gal Post (Roller Shutter)', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Custom Steelwork', N'Yes - Custom Steelwork', 6);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBREARHOODBRUSHSEAL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 50mm', N'Yes - 50mm', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 100mm', N'Yes - 100mm', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 175mm', N'Yes - 175mm', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBSPECIALCONDUIT');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Standard', N'Standard - PVC Grey', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Smooth Walled Sheathed - PVC Grey', N'Smooth Walled Sheathed - PVC Grey', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Corrugated - PVC Orange', N'Corrugated - PVC Orange (DVP)', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'50mm Box Duct', N'50mm Box Duct - White', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Other', N'Other - See Custom Notes', 6);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBCOLOURFINISHTYPE');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Powdercoat', N'Powdercoat', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Painting', N'Painting', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBES40FASCIA');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBES40VSDMTR');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Hyperlift', N'Yes - Hyperlift', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No - GFA DOL', N'No - GFA DOL', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - GFA VSD', N'Yes - GFA VSD', 4);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBHEATTRACELEG');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBGEARBOXHEATER');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBHEATTRACEHOOD');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBFELTSEAL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPED1');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Left', N'Door Column Left', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Right', N'Door Column Right', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Left', N'Side Cover Left', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Right', N'Side Cover Right', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPED2');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Left', N'Door Column Left', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Right', N'Door Column Right', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Left', N'Side Cover Left', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Right', N'Side Cover Right', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBRADAR1');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - No Stalk', N'Falcon Radar - No Stalk', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Short Stalk', N'Falcon Radar - Short Stalk', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Long Stalk', N'Falcon Radar - Long Stalk', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - No Stalk', N'Condor Radar - No Stalk', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Short Stalk', N'Condor Radar - Short Stalk', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Long Stalk', N'Condor Radar - Long Stalk', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - No Stalk', N'IXIO Sensor - No Stalk', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Short Stalk', N'IXIO Sensor - Short Stalk', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Long Stalk', N'IXIO Sensor - Long Stalk', 10);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBRADAR2');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - No Stalk', N'Falcon Radar - No Stalk', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Short Stalk', N'Falcon Radar - Short Stalk', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Long Stalk', N'Falcon Radar - Long Stalk', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - No Stalk', N'Condor Radar - No Stalk', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Short Stalk', N'Condor Radar - Short Stalk', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Long Stalk', N'Condor Radar - Long Stalk', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - No Stalk', N'IXIO Sensor - No Stalk', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Short Stalk', N'IXIO Sensor - Short Stalk', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Long Stalk', N'IXIO Sensor - Long Stalk', 10);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT1');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT2');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT3');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT4');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBFLOORLOOPINSTALL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3rd Party Lay, Seal', N'3rd Party Lay, Seal (No Parts Req)', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Remax Lay, Seal', N'Remax Lay, Seal (Cable, Sikaflex Req)', 3);


-- Friendly labels (the seed uses the raw control name)
UPDATE dbo.uCfgParameters SET Label = N'Door Model' WHERE CfgID = @Cfg AND ControlName = N'CMBDOORMODEL';
UPDATE dbo.uCfgParameters SET Label = N'Door Height (mm)' WHERE CfgID = @Cfg AND ControlName = N'NUMDOORHEIGHT';
UPDATE dbo.uCfgParameters SET Label = N'Door Width (mm)' WHERE CfgID = @Cfg AND ControlName = N'NUMDOORWIDTH';
UPDATE dbo.uCfgParameters SET Label = N'Quantity' WHERE CfgID = @Cfg AND ControlName = N'QTY';
UPDATE dbo.uCfgParameters SET Label = N'GPO / Isolator' WHERE CfgID = @Cfg AND ControlName = N'CMBGPOISO';
UPDATE dbo.uCfgParameters SET Label = N'Hand Crank / Chain Drive' WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORORIDE';
UPDATE dbo.uCfgParameters SET Label = N'Tracks Proud / Conc?' WHERE CfgID = @Cfg AND ControlName = N'CMBTRACKCONFIG';
UPDATE dbo.uCfgParameters SET Label = N'High Wind Tracks Required' WHERE CfgID = @Cfg AND ControlName = N'CMBWINDTRACK';
UPDATE dbo.uCfgParameters SET Label = N'Electrical Spec' WHERE CfgID = @Cfg AND ControlName = N'CMBELECSPEC';
UPDATE dbo.uCfgParameters SET Label = N'Power Supply' WHERE CfgID = @Cfg AND ControlName = N'CMBPOWERSUPPLY';
UPDATE dbo.uCfgParameters SET Label = N'Controller Enclosure' WHERE CfgID = @Cfg AND ControlName = N'CMBCONTROLLERENCLOSURE';
UPDATE dbo.uCfgParameters SET Label = N'Motor Shroud' WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORSHROUD';
UPDATE dbo.uCfgParameters SET Label = N'Brake / VSD Protection' WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORSPEC';
UPDATE dbo.uCfgParameters SET Label = N'Brush Seal' WHERE CfgID = @Cfg AND ControlName = N'CMBBRUSHSEAL';
UPDATE dbo.uCfgParameters SET Label = N'Traffic Light' WHERE CfgID = @Cfg AND ControlName = N'CMBTRAFFICLIGHT';
UPDATE dbo.uCfgParameters SET Label = N'PE Beam' WHERE CfgID = @Cfg AND ControlName = N'CMBPEBEAMS';
UPDATE dbo.uCfgParameters SET Label = N'UPS' WHERE CfgID = @Cfg AND ControlName = N'CMBUPS';
UPDATE dbo.uCfgParameters SET Label = N'Custom Steel Work' WHERE CfgID = @Cfg AND ControlName = N'CMBCUSTSTEEL';
UPDATE dbo.uCfgParameters SET Label = N'Rear Hood Brush Seal' WHERE CfgID = @Cfg AND ControlName = N'CMBREARHOODBRUSHSEAL';
UPDATE dbo.uCfgParameters SET Label = N'Conduit' WHERE CfgID = @Cfg AND ControlName = N'CMBSPECIALCONDUIT';
UPDATE dbo.uCfgParameters SET Label = N'Powdercoat / Painting' WHERE CfgID = @Cfg AND ControlName = N'CMBCOLOURFINISHTYPE';
UPDATE dbo.uCfgParameters SET Label = N'Fascia' WHERE CfgID = @Cfg AND ControlName = N'CMBES40FASCIA';
UPDATE dbo.uCfgParameters SET Label = N'VSD Motor' WHERE CfgID = @Cfg AND ControlName = N'CMBES40VSDMTR';
UPDATE dbo.uCfgParameters SET Label = N'Heat Trace Legs' WHERE CfgID = @Cfg AND ControlName = N'CMBHEATTRACELEG';
UPDATE dbo.uCfgParameters SET Label = N'Gearbox Heater' WHERE CfgID = @Cfg AND ControlName = N'CMBGEARBOXHEATER';
UPDATE dbo.uCfgParameters SET Label = N'Heat Trace In Hood' WHERE CfgID = @Cfg AND ControlName = N'CMBHEATTRACEHOOD';
UPDATE dbo.uCfgParameters SET Label = N'Felt Seal' WHERE CfgID = @Cfg AND ControlName = N'CMBFELTSEAL';
UPDATE dbo.uCfgParameters SET Label = N'Pedestrian Button 1' WHERE CfgID = @Cfg AND ControlName = N'CMBPED1';
UPDATE dbo.uCfgParameters SET Label = N'Pedestrian Button 2' WHERE CfgID = @Cfg AND ControlName = N'CMBPED2';
UPDATE dbo.uCfgParameters SET Label = N'Door Side Radar' WHERE CfgID = @Cfg AND ControlName = N'CMBRADAR1';
UPDATE dbo.uCfgParameters SET Label = N'Non-Door Side Radar' WHERE CfgID = @Cfg AND ControlName = N'CMBRADAR2';
UPDATE dbo.uCfgParameters SET Label = N'Activation 1' WHERE CfgID = @Cfg AND ControlName = N'CMBACT1';
UPDATE dbo.uCfgParameters SET Label = N'Activation 2' WHERE CfgID = @Cfg AND ControlName = N'CMBACT2';
UPDATE dbo.uCfgParameters SET Label = N'Activation 3' WHERE CfgID = @Cfg AND ControlName = N'CMBACT3';
UPDATE dbo.uCfgParameters SET Label = N'Activation 4' WHERE CfgID = @Cfg AND ControlName = N'CMBACT4';
UPDATE dbo.uCfgParameters SET Label = N'Remote Qty 1' WHERE CfgID = @Cfg AND ControlName = N'NUMREMOTEQTY1';
UPDATE dbo.uCfgParameters SET Label = N'Remote Qty 2' WHERE CfgID = @Cfg AND ControlName = N'NUMREMOTEQTY2';
UPDATE dbo.uCfgParameters SET Label = N'Remote Qty 3' WHERE CfgID = @Cfg AND ControlName = N'NUMREMOTEQTY3';
UPDATE dbo.uCfgParameters SET Label = N'Remote Qty 4' WHERE CfgID = @Cfg AND ControlName = N'NUMREMOTEQTY4';
UPDATE dbo.uCfgParameters SET Label = N'Floor Loop Installation' WHERE CfgID = @Cfg AND ControlName = N'CMBFLOORLOOPINSTALL';
UPDATE dbo.uCfgParameters SET Label = N'Hyperlift Motor' WHERE CfgID = @Cfg AND ControlName = N'CHKHYPERLIFT';
UPDATE dbo.uCfgParameters SET Label = N'Hold Open Switch' WHERE CfgID = @Cfg AND ControlName = N'CHKHOLDOPEN';
UPDATE dbo.uCfgParameters SET Label = N'Interlock' WHERE CfgID = @Cfg AND ControlName = N'CHKINTERLOCK';
UPDATE dbo.uCfgParameters SET Label = N'Movisan (Stainless)' WHERE CfgID = @Cfg AND ControlName = N'CHKSTAINLESS';
UPDATE dbo.uCfgParameters SET Label = N'EX35 Felt' WHERE CfgID = @Cfg AND ControlName = N'CHKEX35FELT';
UPDATE dbo.uCfgParameters SET Label = N'Motor Clear Coat' WHERE CfgID = @Cfg AND ControlName = N'CHKMOTORCLEARCOAT';
UPDATE dbo.uCfgParameters SET Label = N'Brake IP Basic' WHERE CfgID = @Cfg AND ControlName = N'CMBBRAKEIPBASIC';
UPDATE dbo.uCfgParameters SET Label = N'Cable Length' WHERE CfgID = @Cfg AND ControlName = N'CMBCABLELENGTH';
UPDATE dbo.uCfgParameters SET Label = N'Curtain Colour' WHERE CfgID = @Cfg AND ControlName = N'CMBCURTAINCOLOUR';
UPDATE dbo.uCfgParameters SET Label = N'Motor Hand' WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORHAND';
UPDATE dbo.uCfgParameters SET Label = N'Activation 5' WHERE CfgID = @Cfg AND ControlName = N'CMBACT5';

SELECT COUNT(*) AS ParametersRestored FROM dbo.uCfgParameters WHERE CfgID = @Cfg;
SELECT COUNT(*) AS OptionsRestored FROM dbo.uCfgParameterOptions o JOIN dbo.uCfgParameters p ON o.ParamID = p.ParamID WHERE p.CfgID = @Cfg;
