/* AUTO-GENERATED from the Python dicts by db/seed_movidor.py. Re-runnable. */
SET NOCOUNT ON;

IF NOT EXISTS (SELECT 1 FROM dbo.uCfgConfigurators WHERE PartID = N'RRD-MOVIDOR-TEMPLATE')
    INSERT INTO dbo.uCfgConfigurators (PartID, PartRevision, PartDescription, ConfiguratorName, DoorType) VALUES (N'RRD-MOVIDOR-TEMPLATE', N'A', N'RRD Movidor configurator template', N'RRD Movidor', N'RRD');
DECLARE @Cfg INT = (SELECT TOP 1 CfgID FROM dbo.uCfgConfigurators WHERE PartID = N'RRD-MOVIDOR-TEMPLATE');
DECLARE @P INT;

-- Clear this configurator's existing definition (idempotent re-run)
DELETE o FROM dbo.uCfgParameterOptions o JOIN dbo.uCfgParameters p ON o.ParamID = p.ParamID WHERE p.CfgID = @Cfg;
DELETE FROM dbo.uCfgParameters WHERE CfgID = @Cfg;
DELETE FROM dbo.uCfgDefaults   WHERE CfgID = @Cfg;

-- Parameters (from movidor_control_names.py)
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBDOORMODEL', N'CMBDOORMODEL', N'dropdown', 1, 1);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMDOORHEIGHT', N'NUMDOORHEIGHT', N'number', 1, 2);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMDOORWIDTH', N'NUMDOORWIDTH', N'number', 1, 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'QTY', N'QTY', N'number', 1, 4);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBGPOISO', N'CMBGPOISO', N'dropdown', 1, 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORORIDE', N'CMBMOTORORIDE', N'dropdown', 1, 6);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBTRACKCONFIG', N'CMBTRACKCONFIG', N'dropdown', 1, 7);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBWINDTRACK', N'CMBWINDTRACK', N'dropdown', 1, 8);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBELECSPEC', N'CMBELECSPEC', N'dropdown', 1, 9);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPOWERSUPPLY', N'CMBPOWERSUPPLY', N'dropdown', 1, 10);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCONTROLLERENCLOSURE', N'CMBCONTROLLERENCLOSURE', N'dropdown', 1, 11);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORSHROUD', N'CMBMOTORSHROUD', N'dropdown', 1, 12);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORSPEC', N'CMBMOTORSPEC', N'dropdown', 1, 13);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBBRUSHSEAL', N'CMBBRUSHSEAL', N'dropdown', 1, 14);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBTRAFFICLIGHT', N'CMBTRAFFICLIGHT', N'dropdown', 1, 15);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPEBEAMS', N'CMBPEBEAMS', N'dropdown', 1, 16);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBUPS', N'CMBUPS', N'dropdown', 1, 17);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCUSTSTEEL', N'CMBCUSTSTEEL', N'dropdown', 1, 18);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBREARHOODBRUSHSEAL', N'CMBREARHOODBRUSHSEAL', N'dropdown', 1, 19);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBSPECIALCONDUIT', N'CMBSPECIALCONDUIT', N'dropdown', 1, 20);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCOLOURFINISHTYPE', N'CMBCOLOURFINISHTYPE', N'dropdown', 1, 21);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBES40FASCIA', N'CMBES40FASCIA', N'dropdown', 1, 22);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBES40VSDMTR', N'CMBES40VSDMTR', N'dropdown', 1, 23);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBHEATTRACELEG', N'CMBHEATTRACELEG', N'dropdown', 1, 24);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBGEARBOXHEATER', N'CMBGEARBOXHEATER', N'dropdown', 1, 25);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBHEATTRACEHOOD', N'CMBHEATTRACEHOOD', N'dropdown', 1, 26);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBFELTSEAL', N'CMBFELTSEAL', N'dropdown', 1, 27);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPED1', N'CMBPED1', N'dropdown', 1, 28);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBPED2', N'CMBPED2', N'dropdown', 1, 29);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBRADAR1', N'CMBRADAR1', N'dropdown', 1, 30);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBRADAR2', N'CMBRADAR2', N'dropdown', 1, 31);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT1', N'CMBACT1', N'dropdown', 1, 32);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT2', N'CMBACT2', N'dropdown', 1, 33);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT3', N'CMBACT3', N'dropdown', 1, 34);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT4', N'CMBACT4', N'dropdown', 1, 35);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY1', N'NUMREMOTEQTY1', N'number', 1, 36);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY2', N'NUMREMOTEQTY2', N'number', 1, 37);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY3', N'NUMREMOTEQTY3', N'number', 1, 38);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'NUMREMOTEQTY4', N'NUMREMOTEQTY4', N'number', 1, 39);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBFLOORLOOPINSTALL', N'CMBFLOORLOOPINSTALL', N'dropdown', 1, 40);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKHYPERLIFT', N'CHKHYPERLIFT', N'checkbox', 1, 41);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKHOLDOPEN', N'CHKHOLDOPEN', N'checkbox', 1, 42);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKINTERLOCK', N'CHKINTERLOCK', N'checkbox', 1, 43);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKSTAINLESS', N'CHKSTAINLESS', N'checkbox', 1, 44);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKEX35FELT', N'CHKEX35FELT', N'checkbox', 1, 45);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CHKMOTORCLEARCOAT', N'CHKMOTORCLEARCOAT', N'checkbox', 1, 46);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBBRAKEIPBASIC', N'CMBBRAKEIPBASIC', N'dropdown', 0, 47);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCABLELENGTH', N'CMBCABLELENGTH', N'dropdown', 0, 48);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBCURTAINCOLOUR', N'CMBCURTAINCOLOUR', N'dropdown', 0, 49);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBMOTORHAND', N'CMBMOTORHAND', N'dropdown', 0, 50);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsVisible, SortOrder) VALUES (@Cfg, N'CMBACT5', N'CMBACT5', N'dropdown', 0, 51);

-- Options (from movidor_option_registery.py, matched to Movidor controls)
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBDOORMODEL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'ES40', N'ES40', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'EX35', N'EX35', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'EX45', N'EX45', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS35', N'HS35', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS35-THERMIC', N'HS35-THERMIC', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS50', N'HS50', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS50-THERMIC', N'HS50-THERMIC', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS65', N'HS65', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVICHILL', N'MOVICHILL', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVICHILL-XL', N'MOVICHILL-XL', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVIFOLD', N'MOVIFOLD', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'CONCERTINA', N'CONCERTINA', 13);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBGPOISO');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'GPO', N'GPO', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Isolator', N'Isolator', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORORIDE');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Hand Crank', N'Hand Crank', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Chain Drive', N'Chain Drive', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBTRACKCONFIG');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Proud', N'Proud', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Concealed', N'Concealed', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBWINDTRACK');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Available', N'Not Available', 4);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBELECSPEC');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Standard', N'Standard', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Carwash', N'Carwash', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPOWERSUPPLY');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P10A', N'1-Ph 10A + N + E', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P15A', N'1-Ph 15A + N + E', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P20A', N'1-Ph 20A + N + E', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P10A', N'3-Ph 10A + N + E', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P15A', N'3-Ph 15A + N + E', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P20A', N'3-Ph 20A + N + E', 7);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBCONTROLLERENCLOSURE');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Std ABS IP54', N'Std ABS IP54', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'ABS Hi-Box IP66', N'ABS Hi-Box IP66', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Remax S/S IP66', N'Remax S/S IP66', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Powdercoated IP66 (S/S)', N'Powdercoated IP66 (S/S)', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORSHROUD');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Stainless Steel Upgrade', N'Yes - Stainless Steel Upgrade', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBMOTORSPEC');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IP65 Std', N'IP65 Std', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IP66 Brake Cover', N'IP66 Brake Cover', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBTRAFFICLIGHT');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPEBEAMS');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1 Level PE', N'1 Level PE', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2 Level PE', N'2 Level PE', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Light Curtain - 1830mm', N'Light Curtain - 1830mm', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1 Level - Slimline', N'1 Level - Slimline', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2x LZRS25', N'2x LZRS25', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBUPS');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No UPS', N'No UPS', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1kVA UPS - 10A', N'1kVA UPS - 10A', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2kVA UPS - 10A', N'2kVA UPS - 10A', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3kVA UPS - 15A', N'3kVA UPS - 15A', 4);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBCUSTSTEEL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'PACKER-DADO', N'Packers - Dado', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'PACKERS', N'Packers - Full Perimeter', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'SOB-1FG', N'1-Fold 3mm Gal', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'SOB-4FG', N'3mm Gal Post (Roller Shutter)', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Custom Steelwork', N'Yes - Custom Steelwork', 6);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBREARHOODBRUSHSEAL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 50mm', N'Yes - 50mm', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 100mm', N'Yes - 100mm', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 175mm', N'Yes - 175mm', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBSPECIALCONDUIT');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Standard', N'Standard - PVC Grey', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Smooth Walled Sheathed - PVC Grey', N'Smooth Walled Sheathed - PVC Grey', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Corrugated - PVC Orange', N'Corrugated - PVC Orange (DVP)', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'50mm Box Duct', N'50mm Box Duct - White', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Other', N'Other - See Custom Notes', 6);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBCOLOURFINISHTYPE');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Powdercoat', N'Powdercoat', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Painting', N'Painting', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBES40FASCIA');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBES40VSDMTR');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Hyperlift', N'Yes - Hyperlift', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No - GFA DOL', N'No - GFA DOL', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - GFA VSD', N'Yes - GFA VSD', 4);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBHEATTRACELEG');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBGEARBOXHEATER');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBHEATTRACEHOOD');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBFELTSEAL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPED1');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Left', N'Door Column Left', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Right', N'Door Column Right', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Left', N'Side Cover Left', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Right', N'Side Cover Right', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBPED2');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Left', N'Door Column Left', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Right', N'Door Column Right', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Left', N'Side Cover Left', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Right', N'Side Cover Right', 5);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBRADAR1');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - No Stalk', N'Falcon Radar - No Stalk', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Short Stalk', N'Falcon Radar - Short Stalk', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Long Stalk', N'Falcon Radar - Long Stalk', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - No Stalk', N'Condor Radar - No Stalk', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Short Stalk', N'Condor Radar - Short Stalk', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Long Stalk', N'Condor Radar - Long Stalk', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - No Stalk', N'IXIO Sensor - No Stalk', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Short Stalk', N'IXIO Sensor - Short Stalk', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Long Stalk', N'IXIO Sensor - Long Stalk', 10);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBRADAR2');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - No Stalk', N'Falcon Radar - No Stalk', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Short Stalk', N'Falcon Radar - Short Stalk', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Long Stalk', N'Falcon Radar - Long Stalk', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - No Stalk', N'Condor Radar - No Stalk', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Short Stalk', N'Condor Radar - Short Stalk', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Long Stalk', N'Condor Radar - Long Stalk', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - No Stalk', N'IXIO Sensor - No Stalk', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Short Stalk', N'IXIO Sensor - Short Stalk', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Long Stalk', N'IXIO Sensor - Long Stalk', 10);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT1');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT2');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT3');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBACT4');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
SET @P = (SELECT ParamID FROM dbo.uCfgParameters WHERE CfgID = @Cfg AND ControlName = N'CMBFLOORLOOPINSTALL');
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3rd Party Lay, Seal', N'3rd Party Lay, Seal (No Parts Req)', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Remax Lay, Seal', N'Remax Lay, Seal (Cable, Sikaflex Req)', 3);

-- Defaults per door model (from movidor_default_defaults.get_default_selections)
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBBRAKEIPBASIC', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBBRUSHSEAL', N'Full Guides (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBCABLELENGTH', N'5');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBCONTROLLERENCLOSURE', N'Std ABS IP54');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBPOWERSUPPLY', N'1P10A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBES40VSDMTR', N'Yes - Hyperlift');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBES40FASCIA', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CHKHYPERLIFT', N'1');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'ES40', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBBRUSHSEAL', N'None (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBCABLELENGTH', N'3');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBCONTROLLERENCLOSURE', N'Std ABS IP54');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBPEBEAMS', N'Light Curtain - 1830mm');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBPOWERSUPPLY', N'1P10A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBPED1', N'In Jbox - Door Side Left');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX35', N'CMBPED2', N'In Jbox - Non Door Side Left');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBBRUSHSEAL', N'None (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBCABLELENGTH', N'3');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBCONTROLLERENCLOSURE', N'Std ABS IP54');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBPEBEAMS', N'Light Curtain - 1830mm');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBPOWERSUPPLY', N'1P10A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBPED1', N'In Jbox - Door Side Left');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'EX45', N'CMBPED2', N'In Jbox - Non Door Side Left');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBBRAKEIPBASIC', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBBRUSHSEAL', N'500 top of Guides (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBCABLELENGTH', N'5');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBCONTROLLERENCLOSURE', N'Std ABS IP54');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBPOWERSUPPLY', N'1P10A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBES40VSDMTR', N'Yes - Hyperlift');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBES40FASCIA', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBBRUSHSEAL', N'Full Guides & Fascia/Hood (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBCABLELENGTH', N'5');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBCONTROLLERENCLOSURE', N'Remax S/S IP66');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBHEATTRACELEG', N'Yes');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBHEATTRACEHOOD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBGEARBOXHEATER', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBPOWERSUPPLY', N'1P15A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBCURTAINCOLOUR', N'B6353-Grey');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS35-THERMIC', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBBRUSHSEAL', N'500 top of Guides (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBCABLELENGTH', N'7');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBCONTROLLERENCLOSURE', N'Std ABS IP54');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBPOWERSUPPLY', N'1P10A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBBRUSHSEAL', N'Full Guides & Fascia/Hood (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBCABLELENGTH', N'5');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBCONTROLLERENCLOSURE', N'Remax S/S IP66');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBHEATTRACELEG', N'Yes');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBHEATTRACEHOOD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBGEARBOXHEATER', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBPOWERSUPPLY', N'1P15A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBCURTAINCOLOUR', N'B6353-Grey');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS50-THERMIC', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBBRUSHSEAL', N'500 top of Guides (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBCABLELENGTH', N'7');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBCONTROLLERENCLOSURE', N'Std ABS IP54');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBPOWERSUPPLY', N'1P10A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'HS65', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBBRUSHSEAL', N'Full Guides & Fascia/Hood (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBCABLELENGTH', N'5');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBCONTROLLERENCLOSURE', N'Remax S/S IP66');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBHEATTRACELEG', N'Yes');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBPOWERSUPPLY', N'1P15A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBFELTSEAL', N'Yes');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBBRUSHSEAL', N'Full Guides & Fascia/Hood (Std)');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBCABLELENGTH', N'5');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBCONTROLLERENCLOSURE', N'Remax S/S IP66');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBHEATTRACELEG', N'Yes');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBPEBEAMS', N'1 Level PE');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBPOWERSUPPLY', N'3P15A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBTRACKCONFIG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBFELTSEAL', N'Yes');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVICHILL-XL', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBBRUSHSEAL', N'None');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBCABLELENGTH', N'7');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBCONTROLLERENCLOSURE', N'Remax Powdercoated IP66');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBPEBEAMS', N'Light Curtain - 1830mm');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBPOWERSUPPLY', N'3P20A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBTRACKCONFIG', N'Concealed');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'MOVIFOLD', N'CMBELECSPEC', N'Carwash');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBBRAKEIPBASIC', N'IP65 Std');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBBRUSHSEAL', N'None');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBCABLELENGTH', N'7');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBCONTROLLERENCLOSURE', N'Remax Powdercoated IP66');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBHEATTRACELEG', N'');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBWINDTRACK', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBMOTORSHROUD', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBPEBEAMS', N'Light Curtain - 1830mm');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBPOWERSUPPLY', N'3P20A');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBTRACKCONFIG', N'Concealed');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBTRAFFICLIGHT', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBFELTSEAL', N'No');
INSERT INTO dbo.uCfgDefaults (CfgID, DoorModel, ControlName, DefaultValue) VALUES (@Cfg, N'CONCERTINA', N'CMBELECSPEC', N'Carwash');

PRINT 'Movidor seed complete.';
