/* Snapshot of RRD-MOVIDOR-TEMPLATE taken 20260817-134535, before the rule + parameter fixes.
   49 parameters, 195 options, 59 rules, 80 conditions.
   Running this file restores exactly that state. */
SET NOCOUNT ON;
DECLARE @Cfg INT = (SELECT TOP 1 CfgID FROM dbo.uCfgConfigurators WHERE PartID = N'RRD-MOVIDOR-TEMPLATE');
DECLARE @P INT;

DELETE o FROM dbo.uCfgParameterOptions o JOIN dbo.uCfgParameters p ON o.ParamID=p.ParamID WHERE p.CfgID=@Cfg;
DELETE FROM dbo.uCfgParameters WHERE CfgID=@Cfg;
DELETE rc FROM dbo.uCfgRuleConditions rc JOIN dbo.uCfgRules r ON rc.RuleID=r.RuleID WHERE r.CfgID=@Cfg;
DELETE FROM dbo.uCfgRules WHERE CfgID=@Cfg;

INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBDOORMODEL', N'Door Model', N'dropdown', 0, 1, 1, N'Rapid Door Configurator');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'ES40', N'ES40', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'EX35', N'EX35', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'EX45', N'EX45', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS35', N'HS35', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS35-THERMIC', N'HS35-THERMIC', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS50', N'HS50', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS50-THERMIC', N'HS50-THERMIC', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'HS65', N'HS65', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVICHILL', N'MOVICHILL', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVICHILL-XL', N'MOVICHILL-XL', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'MOVIFOLD', N'MOVIFOLD', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'CONCERTINA', N'CONCERTINA', 13);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'NUMDOORHEIGHT', N'Door Height (mm)', N'number', 0, 1, 2, N'Rapid Door Configurator');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'NUMDOORWIDTH', N'Door Width (mm)', N'number', 0, 1, 3, N'Rapid Door Configurator');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'QTY', N'Quantity', N'number', 0, 1, 4, N'Rapid Door Configurator');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBPOWERSUPPLY', N'Power Supply', N'dropdown', 0, 1, 5, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P10A', N'1-Ph 10A + N + E', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P15A', N'1-Ph 15A + N + E', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1P20A', N'1-Ph 20A + N + E', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P10A', N'3-Ph 10A + N + E', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P15A', N'3-Ph 15A + N + E', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3P20A', N'3-Ph 20A + N + E', 7);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBGPOISO', N'GPO / Isolator', N'dropdown', 0, 1, 6, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'GPO', N'GPO', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Isolator', N'Isolator', 2);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBMOTORORIDE', N'Hand Crank / Chain Drive', N'dropdown', 0, 1, 7, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Hand Crank', N'Hand Crank', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Chain Drive', N'Chain Drive', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBTRACKCONFIG', N'Tracks Proud / Conc?', N'dropdown', 0, 1, 8, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Proud', N'Proud', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Concealed', N'Concealed', 2);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBWINDTRACK', N'High Wind Tracks Required', N'dropdown', 0, 1, 9, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Available', N'Not Available', 4);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBELECSPEC', N'Electrical Spec', N'dropdown', 0, 1, 10, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Standard', N'Standard', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Carwash', N'Carwash', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBCONTROLLERENCLOSURE', N'Controller Enclosure', N'dropdown', 0, 1, 11, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Std ABS IP54', N'Std ABS IP54', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'ABS Hi-Box IP66', N'ABS Hi-Box IP66', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Remax S/S IP66', N'Remax S/S IP66', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Powdercoated IP66 (S/S)', N'Powdercoated IP66 (S/S)', 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBMOTORSHROUD', N'Motor Shroud', N'dropdown', 0, 1, 12, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Stainless Steel Upgrade', N'Yes - Stainless Steel Upgrade', 2);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBMOTORSPEC', N'Brake / VSD Protection', N'dropdown', 0, 1, 13, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IP65 Std', N'IP65 Std', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IP66 Brake Cover', N'IP66 Brake Cover', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBBRUSHSEAL', N'Brush Seal', N'dropdown', 0, 1, 14, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBTRAFFICLIGHT', N'Traffic Light', N'dropdown', 0, 1, 15, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBPEBEAMS', N'PE Beam', N'dropdown', 0, 1, 16, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1 Level PE', N'1 Level PE', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2 Level PE', N'2 Level PE', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Light Curtain - 1830mm', N'Light Curtain - 1830mm', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1 Level - Slimline', N'1 Level - Slimline', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2x LZRS25', N'2x LZRS25', 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBUPS', N'UPS', N'dropdown', 0, 1, 17, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No UPS', N'No UPS', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'1kVA UPS - 10A', N'1kVA UPS - 10A', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'2kVA UPS - 10A', N'2kVA UPS - 10A', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3kVA UPS - 15A', N'3kVA UPS - 15A', 4);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBCUSTSTEEL', N'Custom Steel Work', N'dropdown', 0, 1, 18, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'PACKER-DADO', N'Packers - Dado', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'PACKERS', N'Packers - Full Perimeter', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'SOB-1FG', N'1-Fold 3mm Gal', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'SOB-4FG', N'3mm Gal Post (Roller Shutter)', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Custom Steelwork', N'Yes - Custom Steelwork', 6);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBREARHOODBRUSHSEAL', N'Rear Hood Brush Seal', N'dropdown', 0, 1, 19, N'UPGRADES / COMMON OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 50mm', N'Yes - 50mm', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 100mm', N'Yes - 100mm', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - 175mm', N'Yes - 175mm', 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBSPECIALCONDUIT', N'Conduit', N'dropdown', 0, 1, 20, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Standard', N'Standard - PVC Grey', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Smooth Walled Sheathed - PVC Grey', N'Smooth Walled Sheathed - PVC Grey', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Corrugated - PVC Orange', N'Corrugated - PVC Orange (DVP)', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'50mm Box Duct', N'50mm Box Duct - White', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Other', N'Other - See Custom Notes', 6);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBCOLOURFINISHTYPE', N'Powdercoat / Painting', N'dropdown', 0, 1, 21, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Powdercoat', N'Powdercoat', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Painting', N'Painting', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBES40FASCIA', N'Fascia', N'dropdown', 0, 1, 22, N'ES40 ONLY');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBES40VSDMTR', N'VSD Motor', N'dropdown', 0, 1, 23, N'ES40 ONLY');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - Hyperlift', N'Yes - Hyperlift', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No - GFA DOL', N'No - GFA DOL', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes - GFA VSD', N'Yes - GFA VSD', 4);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBHEATTRACELEG', N'Heat Trace Legs', N'dropdown', 0, 1, 24, N'THERMIC + MOVICHILL ONLY');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBGEARBOXHEATER', N'Gearbox Heater', N'dropdown', 0, 1, 25, N'THERMIC + MOVICHILL ONLY');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBHEATTRACEHOOD', N'Heat Trace In Hood', N'dropdown', 0, 1, 26, N'THERMIC + MOVICHILL ONLY');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBFELTSEAL', N'Felt Seal', N'dropdown', 0, 1, 27, N'THERMIC + MOVICHILL ONLY');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Yes', N'Yes', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'No', N'No', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBPED1', N'Pedestrian Button 1', N'dropdown', 0, 1, 28, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Left', N'Door Column Left', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Right', N'Door Column Right', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Left', N'Side Cover Left', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Right', N'Side Cover Right', 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBPED2', N'Pedestrian Button 2', N'dropdown', 0, 1, 29, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Left', N'Door Column Left', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Door Column Right', N'Door Column Right', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Left', N'Side Cover Left', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Side Cover Right', N'Side Cover Right', 5);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBRADAR1', N'Door Side Radar', N'dropdown', 0, 1, 30, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - No Stalk', N'Falcon Radar - No Stalk', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Short Stalk', N'Falcon Radar - Short Stalk', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Long Stalk', N'Falcon Radar - Long Stalk', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - No Stalk', N'Condor Radar - No Stalk', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Short Stalk', N'Condor Radar - Short Stalk', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Long Stalk', N'Condor Radar - Long Stalk', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - No Stalk', N'IXIO Sensor - No Stalk', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Short Stalk', N'IXIO Sensor - Short Stalk', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Long Stalk', N'IXIO Sensor - Long Stalk', 10);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBRADAR2', N'Non-Door Side Radar', N'dropdown', 0, 1, 31, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - No Stalk', N'Falcon Radar - No Stalk', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Short Stalk', N'Falcon Radar - Short Stalk', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Falcon Radar - Long Stalk', N'Falcon Radar - Long Stalk', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - No Stalk', N'Condor Radar - No Stalk', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Short Stalk', N'Condor Radar - Short Stalk', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Condor Radar - Long Stalk', N'Condor Radar - Long Stalk', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - No Stalk', N'IXIO Sensor - No Stalk', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Short Stalk', N'IXIO Sensor - Short Stalk', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'IXIO Sensor - Long Stalk', N'IXIO Sensor - Long Stalk', 10);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBACT1', N'Activation 1', N'dropdown', 0, 1, 32, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'NUMREMOTEQTY1', N'Remote Qty 1', N'number', 0, 1, 33, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBACT2', N'Activation 2', N'dropdown', 0, 1, 34, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'NUMREMOTEQTY2', N'Remote Qty 2', N'number', 0, 1, 35, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'NUMREMOTEQTY3', N'Remote Qty 3', N'number', 0, 1, 36, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBACT3', N'Activation 3', N'dropdown', 0, 1, 37, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBACT4', N'Activation 4', N'dropdown', 0, 1, 38, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Not Required', N'Not Required', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Receiver Card Only', N'Elsema Receiver Card Only', 3);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 1 Channel', N'Elsema Remote - 1 Channel', 4);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 2 Channel', N'Elsema Remote - 2 Channel', 5);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Elsema Remote - 4 Channel', N'Elsema Remote - 4 Channel', 6);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Door Side Only', N'Induction Loop - Door Side Only', 7);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Non Door Side Only', N'Induction Loop - Non Door Side Only', 8);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Induction Loop - Both Sides', N'Induction Loop - Both Sides', 9);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Existing Induction Loop', N'Module Only - Existing Floor Loop/s', 10);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - In Wall', N'Magic Switch - In Wall', 11);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Magic Switch - IP65 Housing', N'Magic Switch - IP65 Housing', 12);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pedestrian Switch - Custom Notes', N'Pedestrian Switch - Custom Notes', 13);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Door Side', N'Pull Cord - Door Side', 14);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pull Cord - Non Door Side', N'Pull Cord - Non Door Side', 15);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 2 button Remote', N'Pentacode - 2 button Remote', 16);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Pentacode - 4 button Remote', N'Pentacode - 4 button Remote', 17);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'NUMREMOTEQTY4', N'Remote Qty 4', N'number', 0, 1, 39, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBFLOORLOOPINSTALL', N'Floor Loop Installation', N'dropdown', 0, 1, 40, N'ACTIVATIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'', N'', 1);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'3rd Party Lay, Seal', N'3rd Party Lay, Seal (No Parts Req)', 2);
INSERT INTO dbo.uCfgParameterOptions (ParamID, OptionValue, OptionLabel, SortOrder) VALUES (@P, N'Remax Lay, Seal', N'Remax Lay, Seal (Cable, Sikaflex Req)', 3);
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CHKHYPERLIFT', N'Hyperlift Motor', N'checkbox', 0, 1, 41, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CHKHOLDOPEN', N'Hold Open Switch', N'checkbox', 0, 1, 42, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CHKINTERLOCK', N'Interlock', N'checkbox', 0, 1, 43, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CHKSTAINLESS', N'Movisan (Stainless)', N'checkbox', 0, 1, 44, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CHKEX35FELT', N'EX35 Felt', N'checkbox', 0, 1, 45, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CHKMOTORCLEARCOAT', N'Motor Clear Coat', N'checkbox', 0, 1, 46, N'OPTIONS');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBCABLELENGTH', N'Cable Length', N'dropdown', 0, 1, 47, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBCURTAINCOLOUR', N'Curtain Colour', N'dropdown', 0, 1, 48, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgParameters (CfgID, ControlName, Label, Kind, IsRequired, IsVisible, SortOrder, Section) VALUES (@Cfg, N'CMBMOTORHAND', N'Motor Hand', N'dropdown', 0, 1, 49, N'OVERVIEW');
SET @P = SCOPE_IDENTITY();

INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-01', N'1kVA UPS', N'ASSEMBLY_UPGRADE', N'EL-UPS-1KVAASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBUPS', N'starts_with', N'1kVA');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-02', N'2kVA UPS', N'ASSEMBLY_UPGRADE', N'EL-UPS-2KVAASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBUPS', N'starts_with', N'2kVA');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-03', N'3kVA UPS', N'ASSEMBLY_UPGRADE', N'EL-UPS-3KVAASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBUPS', N'starts_with', N'3kVA');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-04', N'ABS Hi-Box IP66', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-ENC-CONT403015-ABS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCONTROLLERENCLOSURE', N'equals', N'ABS Hi-Box IP66');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'MOVICHILL, HS35-THERMIC, HS50-THERMIC, MOVIFOLD, CONCERTINA');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-05', N'Custom Stainless-Steel IP66', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-ENC-CONT403015-SS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCONTROLLERENCLOSURE', N'equals', N'Custom S/S IP66');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-06', N'Remax Stainless-Steel IP66', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-ENC-CONT403015-RSS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCONTROLLERENCLOSURE', N'equals', N'Remax S/S IP66');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'MOVICHILL, MOVICHILL-XL, HS35-THERMIC, HS50-THERMIC, MOVIFOLD, CONCERTINA');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-07', N'Two-Level PE Beams', N'ASSEMBLY_UPGRADE', N'RRD-PEBASS-D', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBPEBEAMS', N'equals', N'2 Level PE');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-08', N'Heat Trace Hood', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-FREEZERPACK', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBHEATTRACEHOOD', N'equals', N'Yes');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-09', N'Wind Track', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-HWTRK', NULL, N'1', 1, N'Per Door', NULL, 0, N'ROUND((NUMDOORHEIGHT)/100)/10', N'Qty formula: ceil(NUMDOORHEIGHT / 1000)', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBWINDTRACK', N'equals', N'Yes');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-10', N'IP66 Brake Upgrade', N'ASSEMBLY_UPGRADE', N'RRD-GFA-BRAKEPUPG-IP66', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRAKEIPBASIC', N'contains', N'IP66');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKMOTORCLEARCOAT', N'not_checked', NULL);
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBMOTORSPEC', N'not_equals', N'Aggressive / Corrosive');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 2, N'CMBMOTORSPEC', N'equals', N'External / Moisture');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 2, N'CHKMOTORCLEARCOAT', N'not_checked', NULL);
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-11', N'Aggressive Environment Motor', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-MOTUPG-AGGRESSIVE', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKMOTORCLEARCOAT', N'is_checked', NULL);
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 2, N'CMBMOTORSPEC', N'equals', N'Aggressive / Corrosive');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-12', N'ES40 Wide Fascia', N'ASSEMBLY_UPGRADE', N'RRD-FASASS-ES40-4', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'equals', N'ES40');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'NUMDOORWIDTH', N'greater_than', N'3000');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBES40FASCIA', N'equals', N'Yes');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-13', N'Induction Floor Loop Detectors, incl installation', N'ASSEMBLY_UPGRADE', N'OPTION-SENS-FLASS', N'CONCERT/M-FOLD', N'1', 1, N'Per Door', NULL, 0, NULL, N'Also requires an activation starting ''Induction Loop -''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', N'IF(CMBDOORMODEL = "CONCERTINA" or CMBDOORMODEL = "MOVIFOLD", "CONCERT/M-FOLD", IF(CMBDOORMODEL = "MOVICHILL" or CMBDOORMODEL = "HS50-THERMIC" or CMBDOORMODEL = "HS35-THERMIC", "EXCLUDE BOX", "FULL KIT"))');
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBACT1', N'contains', N'Existing Induction Loop');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 2, N'CMBACT2', N'contains', N'Existing Induction Loop');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 3, N'CMBACT3', N'contains', N'Existing Induction Loop');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 4, N'CMBACT4', N'contains', N'Existing Induction Loop');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-17', N'Traffic Light - Rapid Door', N'ASSEMBLY_UPGRADE', N'OPTION-RRD-TLS-4PC', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Also requires Traffic Light not blank.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBTRAFFICLIGHT', N'not_equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'CONCERTINA, MOVIFOLD');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-18', N'Traffic Light - Concertina/Movifold', N'ASSEMBLY_UPGRADE', N'OPTION-INDDR-TLS-2PCRM', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBTRAFFICLIGHT', N'equals', N'Yes');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'CONCERTINA, MOVIFOLD');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-19', N'Powder-Coat Finish', N'ASSEMBLY_UPGRADE', N'OPTION-POWDERCOAT', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Fires when the finish type is not blank.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCOLOURFINISHTYPE', N'in', N'Powdercoat, Painting');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-20', N'Brush Seal - EX', N'ASSEMBLY_UPGRADE', N'OPTION-BBSUPG', N'EX', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'Std');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'None');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'contains', N'EX');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-21', N'Brush Seal - HS25', N'ASSEMBLY_UPGRADE', N'OPTION-BBSUPG', N'HS25', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'Std');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'None');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'equals', N'HS25');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-22', N'Brush Seal - HS35', N'ASSEMBLY_UPGRADE', N'OPTION-BBSUPG', N'HS35', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'Std');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'None');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'equals', N'HS35');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-23', N'Brush Seal - HS50/HS65', N'ASSEMBLY_UPGRADE', N'OPTION-BBSUPG', N'HS65', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'Std');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'None');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'HS50, HS65');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-24', N'Brush Seal - Other Model', N'ASSEMBLY_UPGRADE', N'OPTION-BBSUPG', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Fallback: models that do not match a revision rule above.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'Std');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBBRUSHSEAL', N'not_contains', N'None');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'HS25, HS35, HS50, HS65');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-25', N'Right-Hand Stainless-Steel Motor Cover', N'ASSEMBLY_UPGRADE', N'RRD-MOTCOV-CONC-RH', N'E', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'MOVIFOLD, CONCERTINA');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBMOTORHAND', N'equals', N'Right');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBMOTORSHROUD', N'equals', N'Yes - Stainless Steel Upgrade');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-26', N'Two LZRS25 Sensors', N'MATERIAL_UPGRADE', N'SENS-LZRS25', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBPEBEAMS', N'equals', N'2x LZRS25');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-27', N'IXIO Long Stalk', N'ASSEMBLY_UPGRADE', N'RRD-IXIO-LONGASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''IXIO Sensor - Long Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-28', N'IXIO Short Stalk', N'ASSEMBLY_UPGRADE', N'RRD-IXIO-SHASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''IXIO Sensor - Short Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-29', N'IXIO No Stalk', N'ASSEMBLY_UPGRADE', N'SENS-IXIODT1', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''IXIO Sensor - No Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-30', N'Condor Long Stalk', N'ASSEMBLY_UPGRADE', N'RRD-COND-LONGASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''Condor Radar - Long Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-31', N'Condor Short Stalk', N'ASSEMBLY_UPGRADE', N'RRD-COND-SHASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''Condor Radar - Short Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-32', N'Condor No Stalk', N'MATERIAL_UPGRADE', N'SENS-COND', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''Condor Radar - No Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-33', N'Falcon Long Stalk', N'ASSEMBLY_UPGRADE', N'RRD-FALC-LONGASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''Falcon Radar - Long Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-34', N'Falcon Short Stalk', N'ASSEMBLY_UPGRADE', N'RRD-FALC-SHASS', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''Falcon Radar - Short Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-35', N'Falcon No Stalk', N'MATERIAL_UPGRADE', N'SENS-FALC', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBRADAR1/2 = ''Falcon Radar - No Stalk''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-36', N'Light Curtain', N'MATERIAL_UPGRADE', N'OPTION-LIGHT CURTAIN', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBPEBEAMS', N'contains', N'Curtain');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_contains', N'EX');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'MOVIFOLD, CONCERTINA');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-37', N'Pull Cord', N'MATERIAL_UPGRADE', N'PCSW', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty = count of CMBACT1-4 starting ''Pull Cord''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-38', N'Magic Switch - In Wall', N'MATERIAL_UPGRADE', N'SENS-MAGSW-IW', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY where activation = ''Magic Switch - In Wall''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-39', N'Magic Switch Cable', N'MATERIAL_UPGRADE', N'EL-CAB-1.5140.24CSECWH', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Added x1 with RRD-38. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-40', N'Magic Switch - IP65', N'MATERIAL_UPGRADE', N'SENS-MAGSW-IP65', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY where activation = ''Magic Switch - IP65 Housing''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-41', N'Elsema Receiver', N'MATERIAL_UPGRADE', N'RRD-ELREC1C', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Any CMBACT1-4 starts with ''Elsema Remote'' or ''Elsema Receiver''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-42', N'Pentacode Receiver', N'MATERIAL_UPGRADE', N'RRD-ELREC1C-PC', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Any CMBACT1-4 starts with ''Pentacode - 2'' or ''Pentacode - 4''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-43', N'Pentacode Two-Button Remote', N'MATERIAL_UPGRADE', N'RRD-ELREM2C-PC', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY, activation starts ''Pentacode - 2''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-44', N'Pentacode Four-Button Remote', N'MATERIAL_UPGRADE', N'RRD-ELREM1C-PC', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY, activation starts ''Pentacode - 4''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-45', N'Elsema One-Button Remote', N'MATERIAL_UPGRADE', N'RRD-ELREM1C', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY, activation starts ''Elsema Remote - 1''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-46', N'Elsema Two-Button Remote', N'MATERIAL_UPGRADE', N'RRD-ELREM2C', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY, activation starts ''Elsema Remote - 2''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-47', N'Elsema Four-Button Remote', N'MATERIAL_UPGRADE', N'RRD-ELREM4C', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY, activation starts ''Elsema Remote - 4''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-48', N'Elsema Eight-Button Remote', N'MATERIAL_UPGRADE', N'RRD-ELREM8C', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Qty from NUMREMOTEQTY, activation starts ''Elsema Remote - 8''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-49', N'Hold Open Switch', N'MATERIAL_UPGRADE', N'RRD-SWITCH-TOGGLE-22MM', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKHOLDOPEN', N'is_checked', NULL);
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-50', N'Interlock', N'MATERIAL_UPGRADE', N'OPTION-INTERLOCK', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKINTERLOCK', N'is_checked', NULL);
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-51', N'Chain Operator', N'MATERIAL_UPGRADE', N'OPTION-CHAIN-OPERATOR', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBMOTORORIDE', N'equals', N'Chain Drive');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'HS65, HS50, HS50-THERMIC, CONCERTINA, MOVIFOLD');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-52', N'Rear-Hood Brush Seal', N'MATERIAL_UPGRADE', N'OPTION-REARHOOD-BBSUPG', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBREARHOODBRUSHSEAL', N'contains', N'Yes');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-53', N'Concealed SOB - Large', N'MATERIAL_UPGRADE', N'OPTION-SOB-CONCEALED', N'HS65', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCUSTSTEEL', N'contains', N'SOB-');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBTRACKCONFIG', N'equals', N'Concealed');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'HS50, HS50-THERMIC, HS65');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-54', N'Concealed SOB - Standard', N'MATERIAL_UPGRADE', N'OPTION-SOB-CONCEALED', N'HS35', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCUSTSTEEL', N'contains', N'SOB-');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBTRACKCONFIG', N'equals', N'Concealed');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'CONCERTINA, MOVIFOLD, HS50, HS50-THERMIC, HS65');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-55', N'EX35 Felt Seal', N'MATERIAL_UPGRADE', N'OPTION-RRD-FELTSEAL-PRESSURE', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKEX35FELT', N'is_checked', NULL);
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-56', N'Hyperlift Discount - Small', N'MATERIAL_DISCOUNT', N'OPTION-RRD-HYP-DISCOUNT', N'SML', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKHYPERLIFT', N'is_checked', NULL);
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'EX35, EX45');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-57', N'Hyperlift Discount - Medium', N'MATERIAL_DISCOUNT', N'OPTION-RRD-HYP-DISCOUNT', N'MED', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKHYPERLIFT', N'is_checked', NULL);
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'HS35, HS35-THERMIC');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-58', N'Hyperlift Discount - Large', N'MATERIAL_DISCOUNT', N'OPTION-RRD-HYP-DISCOUNT', N'LGE', N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CHKHYPERLIFT', N'is_checked', NULL);
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'not_in', N'ES40, BUGSTOP, EX35, EX45, HS35, HS35-THERMIC');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-59', N'Heating Discount - IP54', N'MATERIAL_DISCOUNT', N'OPTION-RRD-HEAT1-DISCOUNT', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'MOVICHILL, HS35-THERMIC, HS50-THERMIC');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBGEARBOXHEATER', N'equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBHEATTRACEHOOD', N'equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBHEATTRACELEG', N'equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCONTROLLERENCLOSURE', N'equals', N'Std ABS IP54');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-60', N'Heating Discount - IP66', N'MATERIAL_DISCOUNT', N'OPTION-RRD-HEAT2-DISCOUNT', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, NULL, NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBDOORMODEL', N'in', N'MOVICHILL, HS35-THERMIC, HS50-THERMIC');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBGEARBOXHEATER', N'equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBHEATTRACEHOOD', N'equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBHEATTRACELEG', N'equals', N'No');
INSERT INTO dbo.uCfgRuleConditions (RuleID, GroupNo, ControlName, Operator, CompareValue) VALUES (@P, 1, N'CMBCONTROLLERENCLOSURE', N'contains', N'IP66');
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-61', N'Single Induction Loop Discount', N'MATERIAL_DISCOUNT', N'OPTION-RRD-SINGLELOOP-DISCOUNT', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Activation starts ''Induction Loop -'' AND contains ''Only''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
INSERT INTO dbo.uCfgRules (CfgID, RuleCode, Name, Category, ResultPartID, ResultRevision, Quantity, IsActive, QuantityUnit, AHFactor, SwiPairDoubles, QuantityFormula, Notes, ResultRevisionFormula) VALUES (@Cfg, N'RRD-62', N'Floor Loop Cutting', N'INSTALLATION', N'FLOOR LOOP CUTTING', NULL, N'1', 1, N'Per Door', NULL, 0, NULL, N'Any CMBACT1-4 contains ''Induction Loop -''. Multi-slot: applies across CMBACT1-CMBACT4 / CMBRADAR1-2; set the condition per slot in the editor.', NULL);
SET @P = SCOPE_IDENTITY();
